spring:
  jpa:
    defer-datasource-initialization: on
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver